CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_PRINTK=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_LOG=y


# 1. Zephyr 내장 디버깅 서브시스템 및 기호(Symbol) 정보 활성화
CONFIG_DEBUG=y

# 2. 컴파일러 최적화를 디버깅 최적화(-Og) 모드로 전환
CONFIG_DEBUG_OPTIMIZATIONS=y

# 3. 스레드 이름 정보 분석 및 분석 도구를 위한 정보 노출 활성화
CONFIG_THREAD_NAME=y
CONFIG_THREAD_ANALYZER=y

CONFIG_PARTITION_MANAGER_ENABLED=n